### ISSUE TITLE
[question] Is there any chance of having dedicated citations field

### ISSUE THREAD

**Issue by kirk86** [MaxKuehn/zotero-scholar-citations#10]
Hi, I was wondering if it's possible to get a dedicated citations field instead of using the extra field since zotero stores metadata there?

 For instance,
![image](https://user-images.githubusercontent.com/2902390/68271007-30da7780-0057-11ea-9f8c-b615a6053d25.png)

That would also complicate the sorting of the extra field by the number of citations I presume since it contains additional info not related to the count/number of citations.

**Comment by MaxKuehn** [comment]
Hi,
having a dedicated field would make a lot of things easier on the plugin side, but unfortunately it's nothing that can be fixed on the plugin side. Zotero has to provide a way to create such a field, which is planned for Zotero 5.2. We're not even at 5.1, soo it's still far off. (cf. https://forums.zotero.org/discussion/65301/adding-a-custom-information-field)

Regarding the extra field: the plugin tries to store the ZSC information in front of all other "extra"-field content and preserve whatever information is already in there. Since the citation number is first, the citation count has those leading zeroes and it's just an alphabetical sort you end up with items being sorted according to their citation count, when you sort based on the "extra"-field.
