### ISSUE TITLE
plugin stopped working after a while

### ISSUE THREAD

**Issue by kirk86** [MaxKuehn/zotero-scholar-citations#11]
After having tested the plugin for a couple of days it worked fine but then it stopped working completely. No more ZSCC is shown in the Extra column.

**Comment by MaxKuehn** [comment]
Hi,
I need more information, if I'm to do anything about it. E.g.

- what do you mean with "No more ZSCC is shown in the Extra Column"
    - is there no info showing up when updating new items?
    - is the info just not being updated?
    - is existing info actually being deleted? (most surprising since the plugin has no code for that)
    - etc.
- have you looked into the debug log?
- can you provide a screenshot?

**Comment by kirk86** [comment]
@MaxKuehn Hi,
Just to answer your questions. What happened is what you described in your 1st bullet point.
I don't have an answer on why but after a day or two it started working again. So now I have the exact same experience as before.

> * have you looked into the debug log?

In which location should I look for that?

**Comment by MaxKuehn** [comment]
To see the Debug log: in Zotero
1. Help > "Debug Output Logging" > enable
2. Help > "Debug Output Logging" > "View Output"

from what you're describing and since you're apparently not getting Captchas my best guess is you're getting 429 ("Too Many Requests") Errors. That happens when you try to update too many items at once. Google will block you for a certain amount of time. For how long that is, is logged in the debug log, when you try to update an item, while still being blocked by Google.
