### ISSUE TITLE
restricting the number of author for updating citation

### ISSUE THREAD

**Issue by jakemkc** [MaxKuehn/zotero-scholar-citations#12]
Hi,

Thanks for forking the origin google scholar plugin and updated it for fellow zotero users.

I having been using the plugin for a while, and quite often I encounter the staleness counter in the extra field.

I followed the instruction to check the log and found out that for most of the time, it's caused by too many authors in the google scholar query.

I wonder can you make an option that allows us to restrict the number of author submitted to google? say, first two author only.

Best,
Jake

**Comment by MaxKuehn** [comment]
Hi,

Thx for the info. I'm aware of that issue and plan to fix it in version 2.2 (see [Roadmap|https://github.com/MaxKuehn/zotero-scholar-citations/blob/develop/RoadMap.md])

That
> allow us to restrict the number of author submitted to google?

is a reasonable suggestion, but it's not easy to pick "the correct X" authors. I have seen a lot of items,  where the second or third author is the one causing the issue. So simply restricting the number to a fixed value probably won't do you much good. It might actually make things worse, because you truncate authors from other items.
