### ISSUE TITLE
Subscripts in title 

### ISSUE THREAD

**Issue by ABMalhotra** [MaxKuehn/zotero-scholar-citations#2]
Some papers such as https://science.sciencemag.org/content/360/6390/783 have subscripts in titles, in particular for referencing chemical formulae (e.g. CO**2**, H**2**0).

These don't seem to work well with the current url generator. I tried fixing it in the original repo but my solution was not too successful.

Do you think these can be resolved?

PS: Happy to work with you on this.

**Comment by MaxKuehn** [comment]
Hi, 

First of all thx for the paper. It shows a lot of things that still need fixing. :) Surprisingly number subscript characters seems to be no problem at all.

When I add that paper to Zotero I get 
> CO <sub>2</sub> electroreduction to ethylene via hydroxide-mediated copper catalysis at an abrupt interface

as Title, which obviously won't work. But that's a Zotero import problem and it's better fixed on their side. :( You can only manually fix those for now and maybe consider creating an issue in [Zoteros issue tracker](https://github.com/zotero/zotero/issues)

Assuming we didn't have that problem, I manually substituted the "`<sub>2</sub`>" with a "₂" (an actual UTF-8 subscript 2). With this ZSC generates the following link when trying to look up the citation count
> https://scholar.google.com/scholar?hl=en&as_q=CO%E2%82%82+electroreduction+to+ethylene+via+hydroxide+mediated+copper+catalysis+at+an+abrupt+interface&as_epq=&as_occt=title&num=1&as_sauthors=Dinh+Burdyny+Kibria+Seifitokaldani+Gabardo+Garc%C3%ADa%20de%20Arquer+Kiani+Edwards+De%20Luna+Bushuyev+Zou+Quintero-Bermudez+Pang+Sinton+Sargent&as_ylo=2018&as_yhi=2018

This link unfortunately has no search result, hence the "NoCitationData". There's two reasons for that. 
1. There's some problems with Google Scholar (GS) authors search. The frequency of problems is proportional to the number of authors :/ . For example if an author has no GS account or if the spelling of the name is slightly off the search might fail. This is actually pretty hard to fix, because it involves multiple requests and manipulation of author lists, which is why I put it on the roadmap.
2. Some of the authors have spaces in their names. ZSC doesn't escape them properly and because of that GS interpretes them as multiple authors. E.g. "De Luna" becomes "De" & "Luna". [this is fixable though](https://scholar.google.com/scholar?hl=en&num=1&as_sdt=0%2C5&as_ylo=2018&as_yhi=2018&q=author%3A%22De+Luna%22&btnG=)

If I drop all the authors and the date from the search link like so:

> https://scholar.google.com/scholar?q=allintitle:+CO%E2%82%82+electroreduction+to+ethylene+via+hydroxide+mediated+copper+catalysis+at+an+abrupt+interface&hl=en&num=1&as_sdt=0,5

the first result is the same link you provided. Note that the subscript is in the search bar and GS "correctly" interprets it. (It seems to me they just convert the subscript to actual numbers, but GS indexes paper titles the same way and it ends up working.)

**Comment by ABMalhotra** [comment]
Potential things to watch out for,

What is the "correct" way to store titles in Zotero? For instance, If someone later inserts the citation or generates a bibtex library, the current `<sub>2</sub>` method works well. Would the UTF-8 subscript 2 work?

**Comment by rdaxoc** [comment]
Nevermind #2, I just read that you have it on the roadmap

**Comment by MaxKuehn** [comment]
I can only guess what the "correct" way is, but depending on how you export the items, Zotero does different things.

When I use "Create Bibliography from Items ..." Zotero simply drops those html tags:

> [1]C.-T. Dinh et al., “CO 2 electroreduction to ethylene via hydroxide-mediated copper catalysis at an abrupt interface,” Science, vol. 360, no. 6390, pp. 783–787, May 2018.

while it retains the utf-8 symbol:

> [1]C.-T. Dinh et al., “CO₂ electroreduction to ethylene via hydroxide-mediated copper catalysis at an abrupt interface,” Science, vol. 360, no. 6390, pp. 783–787, May 2018.

The respective BibLaTeX exports look like this:

> title = {{CO} $_{\textrm{2}}$ electroreduction to ethylene via hydroxide-mediated copper catalysis at an abrupt interface}

> title = {{CO}₂ electroreduction to ethylene via hydroxide-mediated copper catalysis at an abrupt interface}

so no problem on the export side. There's one question left: does the program you use those exports in understand utf-8. For example LaTeX does for sure (if configured correctly), but I remember BibTeX throwing errors, because it doesn't support it. BibLaTeX+Biber should be able to handle utf-8 though.

Personally I'd just try choose tools that support utf-8, those that don't are usually ancient/no longer maintained anyway.

**Comment by ABMalhotra** [comment]
Ok awesome, closing this issue because it overlaps with roadmap.
