### ISSUE TITLE
please add reminders when google block you

### ISSUE THREAD

**Issue by ExpectationG** [MaxKuehn/zotero-scholar-citations#4]
Hi! 

thanks for MaxKuehn's work, which help me a lot since the original author has been inactive. 

After I used your plugins to get citations of 200 papers, it didn't update the number of citations and had no any reminders. I wondered why, so I reinstalled it, but it couldn't help. then I installed the plugin of @tele1030, it told me I either need Captcha or was blocked by google. The add-on opens a browser window showed I was blocked by google, which your plugin don't have.

I think you'd better add a reminder when users were banned by google or write this problem into README, when users click the command and nothing happened, we're terrified!

I use windows, zotero 5.0.72 and v.2.0.3 of this plugin.

**Comment by MaxKuehn** [comment]
Hi, 

AFAIK there should be an popup and the captcha page should be displayed, once you get blocked by google. I'll try to make this more configureable & testable, so I can check if it's working correctly without getting myself bot-blocked.

There's some paragraph in the migration section in the README.md about how you should update the cite counts in rather small batches, but yeah, that could be clearer. The whole captcha+botblock+request-batching-topic is **the** Nr.1 issue on my roadmap as well.

**Comment by MaxKuehn** [comment]
Hi again,

I did some testing against a local http server. While the CAPTCHA prompt seems to be working, the localization was broken. As a result when you run into a CAPTCHA you do get a JavaScript alert pop-up, but it doesn't contain the message informing you that you have to solve the CAPTCHA. If you click the pop-up away, the CAPTCHA website is opened in a new Zotero window. Zotero doesn't always seem to highlight the window which makes it sometimes easy to miss.

I can only guess why it didn't work on your end, but here's some suggestions/explanations:
When you update a large number of items you're very likely to run into a 429 ("Too many requests") as well as CAPTCHAs. Right now there's only a hint in the debug log about 429s, because I thought it would be way less of an issue than the CAPTCHAs.

In terms of consequences a 429 actually *is* less of an issue. GS just blocks your requests for a time and informs in the responses you when it's okay to resume. CAPTCHAs on the other hand might last for days if your IP is associated with bot-like behaviour.

I released version 2.0.4 which contains the localization fix and I'll probably add an alert with the 429 timeout and build another release including that.
