### ISSUE TITLE
Not compatible with Zotero 5?

### ISSUE THREAD

**Issue by cbwittig** [MaxKuehn/zotero-scholar-citations#6]
Hi -- I'm having trouble installing this as Zotero says it's not compatible with Zotero version -- I'm running the latest 5.0.61.  Is there something else I can try to install it?  It's an add on I really need for my research and so appreciate your work on this!

**Comment by MaxKuehn** [comment]
Hi,
The latest Zotero version according to [the changelog](https://www.zotero.org/support/changelog) is 5.0.74. Can you update your Zotero? Or do you mean the Zotero Connector?

The earliest version the plugin supports is Zotero Standalone 5.0.66, mostly because that's the version I started developing for. To lower that I would have to go through a lot of manual testing, i.e. install each version and test whether the plugin already/still works. Not upping the min version with every release is already pretty sketchy, considering that I can't automatically test older Zotero versions. :(

**Comment by cbwittig** [comment]
Thank you so much! I’ve been trying to update and it keeps failing, but I’ll contact Zotero. Just knowing it works with 66 helps a lot as that means I can use it. I was worried it was an older version it worked on knowing I couldn’t step back my version. Thank you for the development work on this...it is going to save me much research time!!!

Carol
~ * ~ * ~ * ~ *~ * ~ *~ * ~ *~ * ~ *~ * ~ *
Carol Wittig
Head, Research & Instruction.
179 Research & Collaborative Area, Boatwright Library
FYS Instructor and Adjunct Asst. Professor, SPCS
261 Richmond Way
University of Richmond
804.289.8459

...sent from iPad...


On Sep 18, 2019, at 6:06 AM, MaxKuehn <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
The latest Zotero version according to the changelog<https://www.zotero.org/support/changelog> is 5.0.74. Can you update your Zotero? Or do you mean the Zotero Connector?

The earliest version the plugin supports is Zotero Standalone 5.0.66, mostly because that's the version I started developing for. To lower that I would have to go through a lot of manual testing, i.e. install each version and test whether the plugin already/still works. Not upping the min version with every release is already pretty sketchy, considering that I can't automatically test older Zotero versions. :(

**Comment by MaxKuehn** [comment]
I'll always use the latest Zotero version and test the plugin with that, so that should definitely work.
