### ISSUE TITLE
403 Forbidden from GS

### ISSUE THREAD

**Issue by sanxing-chen** [MaxKuehn/zotero-scholar-citations#7]
Hi, first of all, thank you for keeping this extension working!

I came across a problem after I batch update some of my papers.

The log shows the following:
```
(3)(+0002452): [scholar-citations] GET https://scholar.google.com/scholar?hl=en&as_q=Learning+a+Neural+Semantic+Parser+from+User+Feedback&as_epq=&as_occt=title&num=1&as_sauthors=Iyer+Konstas+Cheung+Krishnamurthy+Zettlemoyer&as_ylo=2017&as_yhi=2017

(3)(+0000390): [scholar-citations] could not retrieve the google scholar data. Server returned: [403: Forbidden]
```

And I use my browser to test it, after going through the CAPTCHAs, the webpage in my browser is actually working while the Add-on still doesn't work (showing 403 again).

Do you have any insight into this situation?

**Comment by MaxKuehn** [comment]
Hi,

personally I've never seen a 403 from GS, but based on how GS behaves in case of 429 here's my guess: (either) Zotero and/or your browser got a cookie from Google. With that cookie (either) your browser is flagged as a legitimate client and/or Zotero is flagged as a bot.

You can delete cookies from Zotero by

1. Edit > Preferences > Advanced > Advanced Configuration > Config Editor

1. Type "cookie" in the search bar

1. set "network.cookie.thirdparty.sessionOnly" to true

1. Restart Zotero

1. reset "network.cookie.thirdparty.sessionOnly" to false

If your browser has said authentication cookie, then there's a chance that all request that do not look like authentic requests coming from a browser are blocked by google for the time being. This includes things like requests with manipulated user-agent strings that some browser add-ons produce, no user-agent string at all, a random user-agent string, etc., but also the ZSC requests that are send via Zotero, because they have some default JavaScript user-agent. 

You can either wait a few (hours/days?) or, if you have a dynamic one, get a new IP address. Both should resolve the problem. (prob. already solved by now)

**Comment by sanxing-chen** [comment]
Thank you for your detailed answer!

You're right, the problem gone after several hours (>10h). I'll trace it next time.
